language: node_js
node_js:
  - 'stable'
notifications:
  email: false
before_install:
  - sudo wget https://github.com/jgm/pandoc/releases/download/2.0.1/pandoc-2.0.1-1-amd64.deb
  - sudo dpkg -i pandoc-2.0.1-1-amd64.deb
